#application: irssinotifier
#version: fcm-10
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
- url: /script
  static_dir: script
- url: /static
  static_dir: static
- url: /cron/clear
  script: cron.app
  login: admin
- url: /.*
  script: main.app
  secure: always
- url: /tasks/gcm
  script: gcmqueuehandler.app
  login: admin
  
libraries:
- name: jinja2
  version: latest
- name: pycrypto
  version: "2.6"
- name: yaml
  version: latest

builtins:
- deferred: on
- appstats: on
